

services:
  # streamlit_app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8501:8501"
  #   volumes:
  #     - .:/app
  #   env_file:
  #     - ./.env
  #   depends_on:
  #     - qdrant
  #     - email_mcp
  #     - scrapeless_mcp
  #     - mongodb
  #     - flask-auth-server

  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333"
  #     - "6334:6334"
  #   volumes:
  #     - qdrant_data:/qdrant/data

  # email_mcp:
  #   build:
  #     context: ./servers/mcp-server-email
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8000:8000" # Assuming email MCP runs on port 8000
  #   volumes:
  #     - ./servers/mcp-server-email:/app/mcp_server_email # Mount the source code

  # scrapeless_mcp:
  #   build:
  #     context: ./servers/scrapeless-mcp-server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8001:8001" # Assuming scrapeless MCP runs on port 8001
  #   volumes:
  #     - ./servers/scrapeless-mcp-server:/app # Mount the source code

  mongo-rest:
    build: ./servers/mongo-rest
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db



volumes:
  qdrant_data:
  mongodb_data: